### PR TITLE
FIX: rework dependency-related twincat items and templating tools

### LINKED ISSUE #249: pytmc template - library enumeration is insufficient
Brought in from ads-deploy, so it has this same issue:
https://github.com/pcdshub/ads-deploy/issues/21

### PR DESCRIPTION
**Pull request by klauer**
Closes #249

Separates and parses out information from library references, placeholders and resolutions.

Using this to generate PLC version information summaries:

https://github.com/pcdshub/plc-summary/blob/master/docs/source/versions.rst

Need to update ads-deploy for per-project dependency version fixes - as some projects are missing them currently.

### CODE REVIEW

**Comment by klauer** [comment]
The generated library dependency summary pages seem to work well enough with this. I think this is in a reviewable state now.

**Review by ZLLentz — APPROVED** [review]
Everything in this diff looks good, and I think the refactoring looks clean/well motivated

**Comment by ZLLentz** [comment]
RE: the linked versions.rst, I have one suggestion: including the git describe output with the repo names. E.g. `lcls-plc-kfe-arbiter/Arbiter @ v1.4.1+4234w2uejhfsdfhbasedf` or however those hashes go. This makes it more clear exactly when and for what repo commits the plc summary page was generated.

**Comment by klauer** [comment]
I like the suggestion and will see about incorporating it. 👍

**Pull request merged**
