### PR TITLE
ENH: add git information to the template tool, if available

### PR DESCRIPTION
**Pull request by klauer**
Partially addresses #251

### CODE REVIEW

**Comment by klauer** [comment]
This is a bit sloppy, but it's working to generate this page currently: https://pcdshub.github.io/plc-summary/index.html

**Comment by ZLLentz** [comment]
Wow, look at all those no-tag plcs!

**Comment by klauer** [comment]
Yeah, that was a bit of a surprise... :(

**Comment by ZLLentz** [comment]
Some of these seem weird, like the kfe one:
v1.3.1-28-gd86661a
Which is 28 tags after v1.3.1, but that commit is tagged at v1.3.4

**Comment by ZLLentz** [comment]
Ahh, it's because the `tc_release` tags are not on `master` branch!

**Comment by klauer** [comment]
Yep - that confused me for way longer than I'd like to admit:
```
lcls-plc-kfe-motion klauer$ git tag
v1.0.0
v1.1.0
v1.2.0
v1.3.0
v1.3.1
v1.3.2
v1.3.3
v1.3.4
lcls-plc-kfe-motion klauer$ git describe --tags
v1.3.1-28-gd86661a
```
And as you noted, the tags are on a separate branch... Not sure if any git-fu can help us out here in an easy/repeatable way.

**Comment by ZLLentz** [comment]
This is all I've got after some googling/experimenting:
```
zlentz@psbuild-rhel7-01$ git describe --contains `git rev-parse HEAD`
v1.3.4~1
zlentz@psbuild-rhel7-01$ vim some_file.txt
zlentz@psbuild-rhel7-01$ git add some_file.txt
zlentz@psbuild-rhel7-01$ git commit -m "test"
[master 6780612] test
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 some_file.txt
zlentz@psbuild-rhel7-01$ git describe --contains `git rev-parse HEAD`
fatal: cannot describe '6780612d1b19edc8ba83c2c40700cd88d4a54143'
zlentz@psbuild-rhel7-01$ git describe --tags
v1.3.1-29-g6780612
```

**Comment by klauer** [comment]
Better, probably:

| pcdshub/lcls-plc-cvmi-motion           | d62467b            | pcdshub/lcls-plc-cvmi-motion Docs           |
|----------------------------------------|--------------------|---------------------------------------------|
| pcdshub/lcls-plc-cvmi-vac              | 837467f            | pcdshub/lcls-plc-cvmi-vac Docs              |
| pcdshub/lcls-plc-hxx-vonhamos          | d39f9be            | pcdshub/lcls-plc-hxx-vonhamos Docs          |
| pcdshub/lcls-plc-kfe-arbiter           | 19a3de4            | pcdshub/lcls-plc-kfe-arbiter Docs           |
| pcdshub/lcls-plc-kfe-gatt              | V0.2.0-6-gd593618  | pcdshub/lcls-plc-kfe-gatt Docs              |
| pcdshub/lcls-plc-kfe-gmd-vac           | v0.1.1-4-g8226a5e  | pcdshub/lcls-plc-kfe-gmd-vac Docs           |
| pcdshub/lcls-plc-kfe-motion            | v1.3.4~1           | pcdshub/lcls-plc-kfe-motion Docs            |
| pcdshub/lcls-plc-kfe-rix-motion        | v1.0.2~1           | pcdshub/lcls-plc-kfe-rix-motion Docs        |
| pcdshub/lcls-plc-kfe-rix-vac           | a74c679            | pcdshub/lcls-plc-kfe-rix-vac Docs           |
| pcdshub/lcls-plc-kfe-vac               | v1.3.1-7-ge9565b7  | pcdshub/lcls-plc-kfe-vac Docs               |
| pcdshub/lcls-plc-kfe-xgmd-vac          | v0.1.1-2-g3b3fdbe  | pcdshub/lcls-plc-kfe-xgmd-vac Docs          |
| pcdshub/lcls-plc-lamp-motion           | 3ed321a            | pcdshub/lcls-plc-lamp-motion Docs           |
| pcdshub/lcls-plc-lamp-vac              | V1.0.0             | pcdshub/lcls-plc-lamp-vac Docs              |
| pcdshub/lcls-plc-las-bts               | e33e626            | pcdshub/lcls-plc-las-bts Docs               |
| pcdshub/lcls-plc-lfe-arbiter           | bc8a287            | pcdshub/lcls-plc-lfe-arbiter Docs           |
| pcdshub/lcls-plc-lfe-gem               | v0.1.0             | pcdshub/lcls-plc-lfe-gem Docs               |
| pcdshub/lcls-plc-lfe-motion            | v1.2.3~1           | pcdshub/lcls-plc-lfe-motion Docs            |
| pcdshub/lcls-plc-lfe-motion-kmono      | ef27946            | pcdshub/lcls-plc-lfe-motion-kmono Docs      |
| pcdshub/lcls-plc-lfe-optics            | v0.0.1-43-g64c48eb | pcdshub/lcls-plc-lfe-optics Docs            |
| pcdshub/lcls-plc-lfe-vac               | e6c5beb            | pcdshub/lcls-plc-lfe-vac Docs               |
| pcdshub/lcls-plc-mfx-be-lens-interlock | 7a797f7            | pcdshub/lcls-plc-mfx-be-lens-interlock Docs |
| pcdshub/lcls-plc-rixs-optics           | V0.1.0-10-gdf16f13 | pcdshub/lcls-plc-rixs-optics Docs           |
| pcdshub/lcls-plc-roving-spectrometer   | bfb3ca5            | pcdshub/lcls-plc-roving-spectrometer Docs   |
| pcdshub/lcls-plc-tmo-motion            | v1.0.0             | pcdshub/lcls-plc-tmo-motion Docs            |
| pcdshub/lcls-plc-tmo-optics            | v0.0.1-62-g0c8e33c | pcdshub/lcls-plc-tmo-optics Docs            |
| pcdshub/lcls-plc-tmo-vac               | d395a4f            | pcdshub/lcls-plc-tmo-vac Docs               |
| pcdshub/lcls-plc-txi-optics            | c0ba66d            | pcdshub/lcls-plc-txi-optics Docs            |
| pcdshub/lcls-plc-vonhamos-motion       | d39f9be            | pcdshub/lcls-plc-vonhamos-motion Docs       |
| pcdshub/sample-delivery-system         | 9258768            | pcdshub/sample-delivery-system Docs         |

**Pull request merged**
